version: '3'

services:
   db:
    build: ./docker/mysql
    volumes:
       - ./docker/mysql/db:/var/lib/mysql
       - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # 初回起動時実行ダンプファイル置き場所
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: test
       MYSQL_USER: test
       MYSQL_PASSWORD: test
       TZ: 'Asia/Tokyo'
    ports:
        - "3306:3306"
   web:
    build: ./docker/apache
    depends_on:
       - db
    ports:
       - "8000:80"
    volumes:
       - .:/var/www/html